import { FormEvent, useEffect, useState } from 'react'
import { API_BASE_URL } from '../config'
export default function Join() { const [open, setOpen] = useState<boolean | null>(null); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { fetch(`${API_BASE_URL}/game-state`).then((r) => r.json()).then((d) => setOpen(d.state.registration_open)).catch(() => setMessage('Kan de registratie niet controleren.')) }, [])
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const r = await fetch(`${API_BASE_URL}/join`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email }) }); const d = await r.json().catch(() => ({})); setMessage(d.message || d.detail || 'Registratie mislukt.'); if (r.ok) { setName(''); setEmail('') }; setBusy(false) }
  if (open === null) return <p className="py-20 text-center text-slate-400">Registratie laden…</p>
  if (!open) return <section className="mx-auto max-w-xl py-20 text-center"><h1 className="text-4xl font-black text-white">Het spel is begonnen</h1><p className="mt-4 text-slate-300">Check je ingevoerde mail voor meer instructies.</p></section>
  return <div className="mx-auto max-w-lg border border-white/10 bg-white/[0.03] p-7"><p className="text-xs uppercase tracking-[0.25em] text-amber-400">Deelnemersregistratie</p><h1 className="mt-3 text-4xl font-black text-white">Doe mee.</h1><p className="mt-3 text-slate-400">Je geheime rol ontvang je per email zodra het spel start.</p><form onSubmit={submit} className="mt-7 space-y-4"><input required minLength={2} value={name} onChange={(e) => setName(e.target.value)} placeholder="Naam" className="field" /><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="field" /><button disabled={busy} className="w-full bg-amber-400 px-4 py-3 font-bold text-slate-950 disabled:opacity-50">{busy ? 'Bezig…' : 'Aanmelden'}</button></form>{message && <p className="mt-4 text-sm text-amber-300">{message}</p>}</div>
}
